import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import csv

Sender_email = 'satyamkashid11@gmail.com'

Sender_password = 'uxcd vyiy yfsq btli'

Subject = 'Hello, this is a test mail'

Message = 'Hello Sir, This Mail is Auto generated by Python Script'

# Email Address from a CSV file
receipient_emails = []

csvfile = open('email_addresses.csv','r')

reader = csv.DictReader(csvfile)
for row in reader:
    receipient_emails.append(row['email'])

smtp_server = 'smtp.gmail.com'
smtp_port = 587  # For TLS
smtp_username = Sender_email
smtp_password = Sender_password
try:
    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()
    server.login(smtp_username, smtp_password)

    for receiver_email in receipient_emails:
        # Create a MIME message
        message = MIMEMultipart()
        message['From'] = Sender_email
        message['To'] = receiver_email
        message['Subject'] = Subject

        # Attach the message body
        message.attach(MIMEText(Message, 'plain'))

        # Send the email
        text = message.as_string()
        server.sendmail(Sender_email, receiver_email, text)
        print(f'Email sent to {receiver_email} successfully!')

except Exception as e:
    print(f'Error: {str(e)}')

finally:
    # Close the SMTP server connection
    server.quit()
