import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import csv

def send_emails(csv_file_path, sender_email, sender_password, subject, message):
    receipient_emails = []

    try:
        with open(csv_file_path, 'r', newline='') as csvfile:
            reader = csv.reader(csvfile)
            next(reader)  # Skip the header row

            for row in reader:
                if len(row) >= 2:  # Ensure there are at least two columns (email and name)
                    receipient_email = row[0].strip()  # Access the first column (email)
                    receipient_name = row[1].strip()   # Access the second column (name)
                    receipient_emails.append({'email': receipient_email, 'string': receipient_name})
                else:
                    print(f"Invalid row: {row}")

        smtp_server = 'smtp.gmail.com'
        smtp_port = 587  # For TLS
        smtp_username = sender_email
        smtp_password = sender_password

        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(smtp_username, smtp_password)

        for receiver_email in receipient_emails:
            # Create a MIME message
            message = MIMEMultipart()
            message['From'] = sender_email
            message['To'] = receiver_email['email']
            message['Subject'] = subject

            # Customize the message body with the recipient's name
            custom_message = f'{receiver_email["string"]},\n{message}'  # Include recipient's name in the message
            message.attach(MIMEText(custom_message, 'plain'))

            # Send the email
            text = message.as_string()
            server.sendmail(sender_email, receiver_email['email'], text)
            print(f'Email sent to {receiver_email["email"]} successfully!')

    except Exception as e:
        print(f'Error: {str(e)}')

    finally:
        # Close the SMTP server connection
        server.quit()

def main():
    if len(sys.argv) != 2:
        print("Usage: python script.py <csv_file>")
        sys.exit(1)

    csv_file_path = sys.argv[1]
    sender_email = 'satyamkashid11@gmail.com'
    sender_password = 'uxcd vyiy yfsq btli'  # Store your password securely, don't keep it in plain text in your script.
    subject = 'Hello, this is a test mail'
    message = 'Hello Sir, This Mail is Auto generated by Python Script'

    send_emails(csv_file_path, sender_email, sender_password, subject, message)

if __name__ == "__main__":
    main()