import pywhatkit as kit
import datetime
import schedule
import time

# Define the recipient's phone number (with country code, e.g., +1 for the US)
to_phone_number = '+919322056418'

# Define the message you want to send
message = 'Hello, this is an automated WhatsApp message ! Generated By Satyam Pls Dont Reply this Message'

# Get the current time
now = datetime.datetime.now()

# Set the time for sending the message (24-hour format)
send_time = now.replace(hour=14, minute=3, second=0)

def SendWhatsappMessage():
# Send the message
    kit.sendwhatmsg(to_phone_number, message, send_time.hour, send_time.minute)
    print("Whatsapp Message Send")

# schedule.every().day.at("15:24").do(SendWhatsappMessage)
# #schedule.every(1).minutes.do(kit.sendwhatmsg(to_phone_number,send_time.hour,send_time.minute))

# #Run the scheduler
# while True:
#     schedule.run_pending()
#     time.sleep(1)
